name: CI/CD to Heroku

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: TypeScript type check
        run: yarn tsc --noEmit

      # - name: Lint
      #   run: yarn lint  # optional

      # - name: Run tests
      #   run: yarn test  # optional

      - name: Build the app
        run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Setup Git Auth for Heroku
        run: |
          git config --global user.email "pkprogrammer1@gmail.com"
          git config --global user.name "pkprogrammer1"
          echo "machine git.heroku.com\n  login ${{ secrets.HEROKU_API_KEY }}\n  password ${{ secrets.HEROKU_API_KEY }}" > ~/.netrc
          
      - name: Deploy to Heroku
        if: success()
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "backend-asadd2723"
          heroku_email: "pkprogrammer1@gmail.com"
          usedocker: false  # unless you're using a Dockerfile
