name: CI/CD to Heroku

on:
  push:
    branches:
      - main  # Trigger only on pushes to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: TypeScript type check
        run: yarn tsc --noEmit

      # Optional lint and test
      # - name: Lint
      #   run: yarn lint
      # - name: Run tests
      #   run: yarn test

      - name: Build the app
        run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        if: success()  # Deploy only if build succeeded
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git config --global user.email "pkprogrammer1@gmail.com"
          git config --global user.name "pkprogrammer1"
          git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/backend-asadd2723.git
          git push heroku HEAD:main -f
